# Tugas 2

## Data Preprocessing

In [2]:
import numpy as np
import pandas as pd

In [6]:
data=pd.read_csv('ShenyangPM.csv',sep=';')
data.head()

No  year  month  day  hour  season  PM_Taiyuanjie  PM_US Post  \
0   1  2010      1    1     0       4            NaN         NaN   
1   2  2010      1    1     1       4            NaN         NaN   
2   3  2010      1    1     2       4            NaN         NaN   
3   4  2010      1    1     3       4            NaN         NaN   
4   5  2010      1    1     4       4            NaN         NaN   

   PM_Xiaoheyan  DEWP   HUMI    PRES  TEMP cbwd     Iws  precipitation  Iprec  
0           NaN -26.0  69.79  1024.0 -22.0   NE  1.0289            NaN    NaN  
1           NaN -26.0  76.26  1024.0 -23.0   NE  2.5722            NaN    NaN  
2           NaN -27.0  69.56  1023.0 -23.0   NE  5.1444            NaN    NaN  
3           NaN -27.0  69.56  1023.0 -23.0   NE  7.7166            NaN    NaN  
4           NaN -27.0  69.56  1022.0 -23.0   NE  9.7744            NaN    NaN

In [4]:
np.sum(data.isnull())

No                   0
year                 0
month                0
day                  0
hour                 0
season               0
PM_Taiyuanjie    28196
PM_US Post       30904
PM_Xiaoheyan     27957
DEWP               692
HUMI               680
PRES               692
TEMP               692
cbwd               692
Iws                692
precipitation    12763
Iprec            12763
dtype: int64

In [5]:
data.describe()

No          year         month           day          hour  \
count  52584.000000  52584.000000  52584.000000  52584.000000  52584.000000   
mean   26292.500000   2012.499772      6.523962     15.726609     11.500000   
std    15179.837614      1.707485      3.448452      8.798896      6.922252   
min        1.000000   2010.000000      1.000000      1.000000      0.000000   
25%    13146.750000   2011.000000      4.000000      8.000000      5.750000   
50%    26292.500000   2012.000000      7.000000     16.000000     11.500000   
75%    39438.250000   2014.000000     10.000000     23.000000     17.250000   
max    52584.000000   2015.000000     12.000000     31.000000     23.000000   

             season  PM_Taiyuanjie   PM_US Post  PM_Xiaoheyan          DEWP  \
count  52584.000000   24388.000000  21680.00000  24627.000000  51892.000000   
mean       2.491100      81.189683     75.83750     75.240468      0.850304   
std        1.116988      80.112376     68.99593     78.404401     14.261483   
min        1.000000       1.000000      1.00000      2.000000    -97.000000   
25%        1.000000      32.000000     31.00000     28.000000    -11.000000   
50%        2.000000      59.000000     57.00000     51.000000      1.000000   
75%        3.000000     103.000000     97.00000     93.000000     14.000000   
max        4.000000    1528.000000    932.00000   1361.000000     28.000000   

               HUMI          PRES          TEMP           Iws  precipitation  \
count  51904.000000  51892.000000  51892.000000  51892.000000   39821.000000   
mean      63.006561   1016.005492      8.460495     19.816487       0.083895   
std       21.883355      9.724308     13.948303     32.135270       0.717721   
min        0.000000    988.000000    -28.000000      0.000000       0.000000   
25%       46.260000   1008.000000     -3.000000      3.000000       0.000000   
50%       64.720000   1016.000000     10.000000      8.000000       0.000000   
75%       82.010000   1024.000000     21.000000     23.000000       0.000000   
max      100.000000   1043.000000     35.000000    465.000000      33.100000   

              Iprec  
count  39821.000000  
mean       0.497750  
std        4.360741  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max      120.000000

In [7]:
data['PM_Taiyuanjie']=data['PM_Taiyuanjie'].fillna((data['PM_Taiyuanjie'].mean()))
data['PM_US Post']=data['PM_US Post'].fillna((data['PM_US Post'].mean()))
data['PM_Xiaoheyan']=data['PM_Xiaoheyan'].fillna((data['PM_Xiaoheyan'].mean()))
data['DEWP']=data['DEWP'].fillna((data['DEWP'].mean()))
data['HUMI']=data['HUMI'].fillna((data['HUMI'].mean()))
data['PRES']=data['PRES'].fillna((data['PRES'].mean()))
data['TEMP']=data['TEMP'].fillna((data['TEMP'].mean()))
data['cbwd']=data['cbwd'].fillna(data['cbwd'].dropna().mode()[0])
data['Iws']=data['Iws'].fillna((data['Iws'].mean()))
data['precipitation']=data['precipitation'].fillna((data['precipitation'].mean()))
data['Iprec']=data['Iprec'].fillna((data['Iprec'].mean()))
np.sum(data.isnull())

No               0
year             0
month            0
day              0
hour             0
season           0
PM_Taiyuanjie    0
PM_US Post       0
PM_Xiaoheyan     0
DEWP             0
HUMI             0
PRES             0
TEMP             0
cbwd             0
Iws              0
precipitation    0
Iprec            0
dtype: int64

### Mengatasi Outlier

In [9]:
from scipy import stats
data1=data.drop('cbwd',1)
data2=data.drop('No',1)
z=np.abs(stats.zscore(data2._get_numeric_data()))
print(z)
data=data[(z<3).all(axis=1)]
print(data.shape)

[[1.43161116 1.61659581 1.6668968  ... 0.75370653 0.36596706 0.43857184]
 [1.43161116 1.61659581 1.6668968  ... 0.67945228 0.36596706 0.43857184]
 [1.43161116 1.61659581 1.6668968  ... 0.55569359 0.36596706 0.43857184]
 ...
 [1.49456997 1.60278094 1.74388767 ... 0.32207152 0.30200832 0.29972018]
 [1.49456997 1.60278094 1.74388767 ... 0.75509702 0.30200832 0.29972018]
 [1.49456997 1.60278094 1.74388767 ... 0.65886913 0.30200832 0.29972018]]
(45294, 17)


In [10]:
data.head(10)

No  year  month  day  hour  season  PM_Taiyuanjie  PM_US Post  \
0   1  2010      1    1     0       4      81.189683     75.8375   
1   2  2010      1    1     1       4      81.189683     75.8375   
2   3  2010      1    1     2       4      81.189683     75.8375   
3   4  2010      1    1     3       4      81.189683     75.8375   
4   5  2010      1    1     4       4      81.189683     75.8375   
5   6  2010      1    1     5       4      81.189683     75.8375   
6   7  2010      1    1     6       4      81.189683     75.8375   
7   8  2010      1    1     7       4      81.189683     75.8375   
8   9  2010      1    1     8       4      81.189683     75.8375   
9  10  2010      1    1     9       4      81.189683     75.8375   

   PM_Xiaoheyan  DEWP   HUMI    PRES  TEMP cbwd      Iws  precipitation  \
0     75.240468 -26.0  69.79  1024.0 -22.0   NE   1.0289       0.083895   
1     75.240468 -26.0  76.26  1024.0 -23.0   NE   2.5722       0.083895   
2     75.240468 -27.0  69.56  1023.0 -23.0   NE   5.1444       0.083895   
3     75.240468 -27.0  69.56  1023.0 -23.0   NE   7.7166       0.083895   
4     75.240468 -27.0  69.56  1022.0 -23.0   NE   9.7744       0.083895   
5     75.240468 -26.0  76.26  1022.0 -23.0   NE  11.8322       0.083895   
6     75.240468 -25.0  76.46  1021.0 -22.0   NE  14.4044       0.083895   
7     75.240468 -24.0  70.26  1021.0 -20.0   NE  16.9766       0.083895   
8     75.240468 -23.0  70.49  1021.0 -19.0   NE  19.0344       0.083895   
9     75.240468 -22.0  70.71  1021.0 -18.0   NE  21.6066       0.083895   

     Iprec  
0  0.49775  
1  0.49775  
2  0.49775  
3  0.49775  
4  0.49775  
5  0.49775  
6  0.49775  
7  0.49775  
8  0.49775  
9  0.49775