# Latihan 4

In [75]:
import numpy as np
import pandas as pd

In [76]:
data=pd.read_csv('WeatherAUS1.csv',sep=';')
data['RainTomorrow'].replace({'No':0,'Yes':1},inplace=True)
data.tail()

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
145455      2.8     23.4       0.0          NaN       NaN           31.0   
145456      3.6     25.3       0.0          NaN       NaN           22.0   
145457      5.4     26.9       0.0          NaN       NaN           37.0   
145458      7.8     27.0       0.0          NaN       NaN           28.0   
145459     14.9      NaN       0.0          NaN       NaN            NaN   

        WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  \
145455          13.0          11.0         51.0         24.0       1024.6   
145456          13.0           9.0         56.0         21.0       1023.5   
145457           9.0           9.0         53.0         24.0       1021.0   
145458          13.0           7.0         51.0         24.0       1019.4   
145459          17.0          17.0         62.0         36.0       1020.2   

        Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RISK_MM  \
145455       1020.3       NaN       NaN     10.1     22.4      0.0   
145456       1019.1       NaN       NaN     10.9     24.5      0.0   
145457       1016.8       NaN       NaN     12.5     26.1      0.0   
145458       1016.5       3.0       2.0     15.1     26.0      0.0   
145459       1017.9       8.0       8.0     15.0     20.9      NaN   

        RainTomorrow  
145455           0.0  
145456           0.0  
145457           0.0  
145458           0.0  
145459           NaN

In [77]:
data.describe()

MinTemp        MaxTemp       Rainfall   Evaporation  \
count  143975.000000  144199.000000  142199.000000  82670.000000   
mean       12.194034      23.221348       2.360918      5.468232   
std         6.398495       7.119049       8.478060      4.193704   
min        -8.500000      -4.800000       0.000000      0.000000   
25%         7.600000      17.900000       0.000000      2.600000   
50%        12.000000      22.600000       0.000000      4.800000   
75%        16.900000      28.200000       0.800000      7.400000   
max        33.900000      48.100000     371.000000    145.000000   

           Sunshine  WindGustSpeed   WindSpeed9am   WindSpeed3pm  \
count  75625.000000  135197.000000  143693.000000  142398.000000   
mean       7.611178      40.035230      14.043426      18.662657   
std        3.785483      13.607062       8.915375       8.809800   
min        0.000000       6.000000       0.000000       0.000000   
25%        4.800000      31.000000       7.000000      13.000000   
50%        8.400000      39.000000      13.000000      19.000000   
75%       10.600000      48.000000      19.000000      24.000000   
max       14.500000     135.000000     130.000000      87.000000   

         Humidity9am    Humidity3pm   Pressure9am    Pressure3pm  \
count  142806.000000  140953.000000  130395.00000  130432.000000   
mean       68.880831      51.539116    1017.64994    1015.255889   
std        19.029164      20.795902       7.10653       7.037414   
min         0.000000       0.000000     980.50000     977.100000   
25%        57.000000      37.000000    1012.90000    1010.400000   
50%        70.000000      52.000000    1017.60000    1015.200000   
75%        83.000000      66.000000    1022.40000    1020.000000   
max       100.000000     100.000000    1041.00000    1039.600000   

           Cloud9am      Cloud3pm        Temp9am       Temp3pm        RISK_MM  \
count  89572.000000  86102.000000  143693.000000  141851.00000  142193.000000   
mean       4.447461      4.509930      16.990631      21.68339       2.360682   
std        2.887159      2.720357       6.488753       6.93665       8.477969   
min        0.000000      0.000000      -7.200000      -5.40000       0.000000   
25%        1.000000      2.000000      12.300000      16.60000       0.000000   
50%        5.000000      5.000000      16.700000      21.10000       0.000000   
75%        7.000000      7.000000      21.600000      26.40000       0.800000   
max        9.000000      9.000000      40.200000      46.70000     371.000000   

        RainTomorrow  
count  142193.000000  
mean        0.224181  
std         0.417043  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000

In [58]:
np.sum(data.isnull())

MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustSpeed    10263
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RISK_MM           3267
RainTomorrow      3267
dtype: int64

In [78]:
print(data.shape)

(145460, 18)


In [73]:
data.tail()

MinTemp    MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
145455      2.8  23.400000       0.0     5.468232  7.611178       31.00000   
145456      3.6  25.300000       0.0     5.468232  7.611178       22.00000   
145457      5.4  26.900000       0.0     5.468232  7.611178       37.00000   
145458      7.8  27.000000       0.0     5.468232  7.611178       28.00000   
145459     14.9  23.221348       0.0     5.468232  7.611178       40.03523   

        WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  \
145455          13.0          11.0         51.0         24.0       1024.6   
145456          13.0           9.0         56.0         21.0       1023.5   
145457           9.0           9.0         53.0         24.0       1021.0   
145458          13.0           7.0         51.0         24.0       1019.4   
145459          17.0          17.0         62.0         36.0       1020.2   

        Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm   RISK_MM  \
145455       1020.3  4.447461   4.50993     10.1     22.4  0.000000   
145456       1019.1  4.447461   4.50993     10.9     24.5  0.000000   
145457       1016.8  4.447461   4.50993     12.5     26.1  0.000000   
145458       1016.5  3.000000   2.00000     15.1     26.0  0.000000   
145459       1017.9  8.000000   8.00000     15.0     20.9  2.360682   

        RainTomorrow  
145455           0.0  
145456           0.0  
145457           0.0  
145458           0.0  
145459           0.0

In [79]:
data['MinTemp']=data['MinTemp'].fillna((data['MinTemp'].mean()))
data['MaxTemp']=data['MaxTemp'].fillna((data['MaxTemp'].mean()))
data['Rainfall']=data['Rainfall'].fillna((data['Rainfall'].mean()))
data['Evaporation']=data['Evaporation'].fillna((data['Evaporation'].mean()))
data['Sunshine']=data['Sunshine'].fillna((data['Sunshine'].mean()))
data['WindGustSpeed']=data['WindGustSpeed'].fillna((data['WindGustSpeed'].mean()))
data['WindSpeed9am']=data['WindSpeed9am'].fillna((data['WindSpeed9am'].mean()))
data['WindSpeed3pm']=data['WindSpeed3pm'].fillna((data['WindSpeed3pm'].mean()))
data['Humidity9am']=data['Humidity9am'].fillna((data['Humidity9am'].mean()))
data['Humidity3pm']=data['Humidity3pm'].fillna((data['Humidity3pm'].mean()))
data['Pressure9am']=data['Pressure9am'].fillna((data['Pressure9am'].mean()))
data['Pressure3pm']=data['Pressure3pm'].fillna((data['Pressure3pm'].mean()))
data['Cloud9am']=data['Cloud9am'].fillna((data['Cloud9am'].mean()))
data['Cloud3pm']=data['Cloud3pm'].fillna((data['Cloud3pm'].mean()))
data['Temp9am']=data['Temp9am'].fillna((data['Temp9am'].mean()))
data['Temp3pm']=data['Temp3pm'].fillna((data['Temp3pm'].mean()))
data['RISK_MM']=data['RISK_MM'].fillna((data['RISK_MM'].mean()))
data['RISK_MM']=data['RISK_MM'].fillna((data['RISK_MM'].mean()))
data['RainTomorrow'].fillna((data.RainTomorrow.mode())[0],inplace=True)
np.sum(data.isnull())

MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustSpeed    0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RISK_MM          0
RainTomorrow     0
dtype: int64

In [82]:
from scipy import stats
z=np.abs(stats.zscore(data._get_numeric_data()))
print(z)
data=data[(z<3).all(axis=1)]
print(data.shape)

[[0.22562535 0.03819883 0.22470698 ... 0.02234639 0.38331232 0.49216508]
 [0.73049893 0.28243552 0.3863391  ... 0.39939352 0.38331232 0.49216508]
 [0.14594832 0.36988125 0.3863391  ... 0.23349278 0.38331232 0.49216508]
 ...
 [1.04920703 0.54477272 0.3863391  ... 0.67086745 0.38331232 0.49216508]
 [0.66675732 0.55934701 0.3863391  ... 0.65578556 0.38331232 0.49216508]
 [0.46465642 0.00863539 0.3863391  ... 0.11339057 0.25560875 0.49216508]]
(123167, 18)


In [81]:
from sklearn.preprocessing import normalize
xnorm=normalize(data,norm='l2') 
xnorm=pd.DataFrame(xnorm) 
xnorm.tail()

0         1    2         3         4         5         6   \
134748  0.001934  0.016161  0.0  0.003777  0.005257  0.021410  0.008978   
134749  0.002489  0.017492  0.0  0.003781  0.005262  0.015211  0.008988   
134750  0.003742  0.018639  0.0  0.003789  0.005274  0.025637  0.006236   
134751  0.005410  0.018728  0.0  0.003793  0.005279  0.019422  0.009017   
134752  0.010317  0.016078  0.0  0.003786  0.005270  0.027720  0.011771   

              7         8         9         10        11        12        13  \
134748  0.007597  0.035222  0.016575  0.707626  0.704656  0.003072  0.003115   
134749  0.006223  0.038718  0.014519  0.707643  0.704601  0.003075  0.003118   
134750  0.006236  0.036723  0.016629  0.707433  0.704523  0.003082  0.003125   
134751  0.004855  0.035376  0.016647  0.707095  0.705083  0.002081  0.001387   
134752  0.011771  0.042928  0.024926  0.706381  0.704789  0.005539  0.005539   

              14        15        16   17  
134748  0.006975  0.015470  0.000000  0.0  
134749  0.007536  0.016939  0.000000  0.0  
134750  0.008661  0.018084  0.000000  0.0  
134751  0.010474  0.018035  0.000000  0.0  
134752  0.010386  0.014471  0.001635  0.0

## feature selection

In [90]:
from sklearn.feature_selection import SelectKBest, chi2
X=data.drop(columns=['RainTomorrow'])
y=data[['RainTomorrow']]
selector = SelectKBest(chi2,k='all').fit(X,y)
X_new=selector.transform(X)
scores=selector.scores_